### ISSUE TITLE
Feature request: use fast version of WatchService on OS X

### ISSUE THREAD

**Issue by thomasjm** [derekchiang/Clojure-Watch#4]
Clojure-Watch is pretty slow on OS X, I think because of the issue described in this question: http://stackoverflow.com/questions/9588737/is-java-7-watchservice-slow-for-anyone-else. "JDK 7 does not yet have a native implementation of WatchService for MacOS. Rather than listening for native file system events, it uses the fallback sun.nio.fs.PollingWatchService."

Feature request: make Clojure-Watch on OS X use a native WatchService like  https://github.com/gjoseph/BarbaryWatchService

Thanks!

**Comment by derekchiang** [comment]
Solved by https://github.com/derekchiang/Clojure-Watch/pull/3
